//整个应用程序周期里的数据控制
App({
    globalData:{
        g_musicStatus:false,
        g_bgmPage:null,
        doubanAPIBase:"https://api.douban.com"
    },
    onLaunch:function(){
        wx.onBackgroundAudioPlay(function(){
            this.globalData.g_musicStatus=true;
        });
        wx.onBackgroundAudioPause(function(){
            this.globalData.g_musicStatus=false;
        })
    }
})